### PR TITLE
Update docs build script

### PR DESCRIPTION
**Pull request by victoriadrake**
Commit https://github.com/victoriadrake/hugo-theme-introduction/commit/c2aecb80c0eb23bb6911d95be1abdc93682cb7d2 seems to have broken the Netlify demo site asset links.

### CODE REVIEW

**Comment by victoriadrake** [comment]
@hanzei You may need to update a local script?

**Comment by hanzei** [comment]
Maybe. Is `/docs` still in use?

**Comment by VincentTam** [comment]
> Commit [c2aecb8](https://github.com/victoriadrake/hugo-theme-introduction/commit/c2aecb80c0eb23bb6911d95be1abdc93682cb7d2) seems to have broken the Netlify demo site asset links.

The linked commit refers to #159, which intends to be a code refactoring so that the code base complies with the [advices on Hugo Discourse](https://discourse.gohugo.io/t/hugo-themes-donts/17714?u=vincenttam) written by [the collaborator of the Hugo themes repo](https://github.com/gohugoio/hugoThemes/issues/created_by/onedrawingperday).

> Make sure not to use a forward slash `/` in the beginning of a `URL`, because it will point to the host root and Hugo will not generate the correct URL for the demo's assets.

I have no intention to break the `docs/` folder.

Please review #163, which shares the same goal of #159.

**Comment by victoriadrake** [comment]
> Maybe. Is `/docs` still in use?

@hanzei  Yes, the Netlify demo site builds from it.

**Pull request merged**
