### PR TITLE
Fix issue-236

### PR DESCRIPTION
**Pull request by thegreatluke**
Added support to list custom taxonomies on single blog pages.

### CODE REVIEW

**Comment by thegreatluke** [comment]
Technically this could replace the current logic that add's the "tag" taxonomy but I left that in place since. Open to any suggestions if this isn't quite what you were looking for.

**Comment by victoriadrake** [comment]
This works great!

> Technically this could replace the current logic that add's the "tag" taxonomy but I left that in place since.

I agree this could replace those lines, I think it would work just the same. Do you want to make that update in this PR, Luke?

**Comment by thegreatluke** [comment]
Sure, I’ll work on that and update the PR.

**Comment by thegreatluke** [comment]
As I look at this. One thing I notice is that removing the code block specifically deals with the "Tag" parameter makes it a little unpredictable which order the taxonomies will appear in.

For example, if I use a "series" taxonomy it will appear above "tags". 

I guess the question is. Is that an acceptable outcome? i.e. Do you want to force Tags to be listed first (as it is now), or do you want to find some way to control the order?

**Comment by victoriadrake** [comment]
I’m not personally concerned with the order they show up in, so it’s acceptable to me. If someone wants to control that behavior in the future I’d welcome an issue and PR, but for now I’d say go ahead!

**Comment by thegreatluke** [comment]
I'm still getting the hang of git and learning the best practices for committing code to projects. Hopefully, this all got updated with the changes I made. Looks like GitHub does all the work for me behind the scenes. If so I think this is ready.

**Comment by victoriadrake** [comment]
I'm not sure what part GitHub played in it, but your commits look tidy to me! I see 5 commits on top of `master` for this branch.

The correct tags show up, however the links are not properly rendered. The first tag links to the taxonomy page instead of the tag itself, and it appears that any taxonomy terms beyond the first one do not render as links:

Screenshot from 2020-10-03 10-21-00

Do you want to take a crack at a fix, or would you like some help?

**Comment by thegreatluke** [comment]
You are definitely correct on this. 

I've been plugging away at this and I think I've figured it out after reusing some of your original code as a template. I'll submit an updated PR a little later this evening or tomorrow morning after I do a little more testing.

**Comment by victoriadrake** [comment]
Looks like this works great! Thank you so much again, Luke!

**Pull request merged**
