### PR TITLE
adding optional logo

### PR DESCRIPTION
**Pull request by Athanasiamo**
some small adjustments to add logo to site

### CODE REVIEW

**Comment by victoriadrake** [comment]
Thank you for the PR!

The logo appears very large on the home page - is this intentional? I feel like it takes away from the minimalist approach this theme strives for.

**Comment by Athanasiamo** [comment]
it was intentional, and from a personal taste on my own page. However, I do see your point.
How about an option for size? I dont know if you have an ideal of not having too many parameters to set in the toml, but I think if one opts for a logo, then giving them the option for the size on the home page also makes sense, as it would depend on the logo, the colours etc how the logo is perceived.

**Comment by Athanasiamo** [comment]
I added an option for logo size on the main page.

Sorry for a bit of commit in there that should not have been in this branch. 
I'm preparing another PR for another feature and a little bled into the history here.

**Comment by victoriadrake** [comment]
I'm willing to let others weigh in on whether they would like to have a logo option in this theme, however, I can't move this PR forward with unrelated changes included. Would you like to try removing the unrelated files and changes?

**Comment by Athanasiamo** [comment]
Closing this PR in favor of [this one](https://github.com/victoriadrake/hugo-theme-introduction/pull/213). Sorry for the messy PRs, should not have been working from my master branch.

**Pull request closed without merging**
