### PR TITLE
add Logo option

### PR DESCRIPTION
**Pull request by Athanasiamo**
Sorry for the messy PR, but the [other PR](https://github.com/victoriadrake/hugo-theme-introduction/pull/205) is from master where there is other work. I have in this branch attempted to get things cleaned up so that it is only the new logo option that remains.

### CODE REVIEW

**Comment by victoriadrake** [comment]
Thank you for tidying up this PR! Now I can see clearly what was changed. 😄

A few thoughts:

Can you explain the reasons for moving the `hero` into a partial?

I would prefer that the inlined styles added [here](https://github.com/victoriadrake/hugo-theme-introduction/blob/25e94ab5bab8958a7923feaaafabcb006fa7aa58/layouts/_default/baseof.html#L17) were instead placed in the Sass files, with the exception of `background-image` and `background-size` which get variables from the site config.

I worry that the logo makes it a little harder to read the text in front of it on some screens:

Screenshot_20200614_145405

We may want to check the contrast of the colors using something like https://contrastchecker.com/ to make sure that persons without good vision can read it okay.

Thank you for your hard work on this!

**Comment by Athanasiamo** [comment]
I got a little more comfortable with sass working on the grid styles, so I think I am up to moving the style changes into the sass. I'll get to work on that asap. 

I moved the hero into a partial because I found it cleaner that way. The hero contains quite a lot at the moment, and I though it was making the main document hard to navigate. But that might be a personal preference. if you prefer it directly stated in the main file, I will put it back there.

I agree, the logo and colours in the example site are absolutely making it hard to read. I think it will likely depend a lot on the logo and the colours chosen for the site whether or not adding the logo to the hero is a good idea.  For instance, on my page the colours for the page, and the style of the logo makes it look nice (imo), but the example site (and the logo I made for it) is not ideal.

image

It is easy to see and imagine instances where a logo and the site colours would interfere and make reading hard. The logo for the example site could also use the secondary colour in stead, which would interfere less.

**Comment by victoriadrake** [comment]
Is there a way to ensure it will always be easy to read text over the logo, no matter what the image is? It will be difficult for most users, I think, to make or create an image that is friendly to this purpose.

Perhaps an opacity setting on the image?

**Comment by Athanasiamo** [comment]
an opacity setting might not be a bad idea. I can have a look at how that might work out for this.

**Comment by Athanasiamo** [comment]
still working on this.

**Comment by Athanasiamo** [comment]
Hope to get back to this very soon.

**Pull request closed without merging**
